-- MySQL Script generated by MySQL Workbench
-- Sun Jun 14 18:13:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Gerenciador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Gerenciador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Gerenciador` DEFAULT CHARACTER SET utf8 ;
USE `Gerenciador` ;

-- -----------------------------------------------------
-- Table `Gerenciador`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gerenciador`.`Usuario` (
  `idUsuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gerenciador`.`TipoDaQuestao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gerenciador`.`TipoDaQuestao` (
  `idTipoDaQuestao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTipoDaQuestao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gerenciador`.`AreaDeConhecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gerenciador`.`AreaDeConhecimento` (
  `idAreaDeConhecimento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  PRIMARY KEY (`idAreaDeConhecimento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gerenciador`.`Assunto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gerenciador`.`Assunto` (
  `idAssunto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idAssunto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gerenciador`.`NivelDeDificuldade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gerenciador`.`NivelDeDificuldade` (
  `idNivelDeDificuldade` INT UNSIGNED NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idNivelDeDificuldade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gerenciador`.`Questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gerenciador`.`Questao` (
  `idQuestao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(100) NULL,
  `idResponsavel` INT UNSIGNED NOT NULL,
  `idTipoDaQuestao` INT UNSIGNED NOT NULL,
  `idAreaDeConhecimento` INT UNSIGNED NOT NULL,
  `idAssunto` INT UNSIGNED NOT NULL,
  `IdNivelDeDificuldade` INT UNSIGNED NOT NULL,
  `DataCadastramento` DATE NOT NULL,
  `Imagem` TEXT NULL,
  PRIMARY KEY (`idQuestao`),
  INDEX `fk_Questao_Usuario1_idx` (`idResponsavel` ASC) VISIBLE,
  INDEX `fk_Questao_TipoDaQuestao1_idx` (`idTipoDaQuestao` ASC) VISIBLE,
  INDEX `fk_Questao_AreaDeConhecimento1_idx` (`idAreaDeConhecimento` ASC) VISIBLE,
  INDEX `fk_Questao_Assunto1_idx` (`idAssunto` ASC) VISIBLE,
  INDEX `fk_Questao_NivelDeDificuldade1_idx` (`IdNivelDeDificuldade` ASC) VISIBLE,
  CONSTRAINT `fk_Questao_Usuario1`
    FOREIGN KEY (`idResponsavel`)
    REFERENCES `Gerenciador`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Questao_TipoDaQuestao1`
    FOREIGN KEY (`idTipoDaQuestao`)
    REFERENCES `Gerenciador`.`TipoDaQuestao` (`idTipoDaQuestao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Questao_AreaDeConhecimento1`
    FOREIGN KEY (`idAreaDeConhecimento`)
    REFERENCES `Gerenciador`.`AreaDeConhecimento` (`idAreaDeConhecimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Questao_Assunto1`
    FOREIGN KEY (`idAssunto`)
    REFERENCES `Gerenciador`.`Assunto` (`idAssunto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Questao_NivelDeDificuldade1`
    FOREIGN KEY (`IdNivelDeDificuldade`)
    REFERENCES `Gerenciador`.`NivelDeDificuldade` (`idNivelDeDificuldade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gerenciador`.`QuestaoMultipla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gerenciador`.`QuestaoMultipla` (
  `idQuestaoMultipla` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Itens` VARCHAR(100) NOT NULL,
  `Item_Correto` CHAR(1) NOT NULL,
  `Questao_idQuestao` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idQuestaoMultipla`),
  INDEX `fk_QuestaoMultipla_Questao1_idx` (`Questao_idQuestao` ASC) VISIBLE,
  CONSTRAINT `fk_QuestaoMultipla_Questao1`
    FOREIGN KEY (`Questao_idQuestao`)
    REFERENCES `Gerenciador`.`Questao` (`idQuestao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gerenciador`.`Semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gerenciador`.`Semestre` (
  `idSemestre` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSemestre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gerenciador`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gerenciador`.`Disciplina` (
  `idCodDisciplina` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCodDisciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gerenciador`.`Prova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gerenciador`.`Prova` (
  `idProva` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DataPrevista` DATE NOT NULL,
  `idSemestre` INT UNSIGNED NOT NULL,
  `idCodDisciplina` INT UNSIGNED NOT NULL,
  `idUsuario` INT UNSIGNED NOT NULL,
  `idAssunto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idProva`),
  INDEX `fk_Prova_Semestre1_idx` (`idSemestre` ASC) VISIBLE,
  INDEX `fk_Prova_Disciplina1_idx` (`idCodDisciplina` ASC) VISIBLE,
  INDEX `fk_Prova_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Prova_Assunto1_idx` (`idAssunto` ASC) VISIBLE,
  CONSTRAINT `fk_Prova_Semestre1`
    FOREIGN KEY (`idSemestre`)
    REFERENCES `Gerenciador`.`Semestre` (`idSemestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prova_Disciplina1`
    FOREIGN KEY (`idCodDisciplina`)
    REFERENCES `Gerenciador`.`Disciplina` (`idCodDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prova_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Gerenciador`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prova_Assunto1`
    FOREIGN KEY (`idAssunto`)
    REFERENCES `Gerenciador`.`Assunto` (`idAssunto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gerenciador`.`Questao_Prova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gerenciador`.`Questao_Prova` (
  `idQuestao_Provacol` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Questao_idQuestao` INT UNSIGNED NOT NULL,
  `Prova_idProva` INT UNSIGNED NOT NULL,
  `idSemestre` INT UNSIGNED NOT NULL,
  `idNivelDeDificuldade` INT UNSIGNED NOT NULL,
  INDEX `fk_Questao_Prova_Questao1_idx` (`Questao_idQuestao` ASC) VISIBLE,
  INDEX `fk_Questao_Prova_Prova1_idx` (`Prova_idProva` ASC) VISIBLE,
  PRIMARY KEY (`idQuestao_Provacol`),
  INDEX `fk_Questao_Prova_Semestre1_idx` (`idSemestre` ASC) VISIBLE,
  INDEX `fk_Questao_Prova_NivelDeDificuldade1_idx` (`idNivelDeDificuldade` ASC) VISIBLE,
  CONSTRAINT `fk_Questao_Prova_Questao1`
    FOREIGN KEY (`Questao_idQuestao`)
    REFERENCES `Gerenciador`.`Questao` (`idQuestao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Questao_Prova_Prova1`
    FOREIGN KEY (`Prova_idProva`)
    REFERENCES `Gerenciador`.`Prova` (`idProva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Questao_Prova_Semestre1`
    FOREIGN KEY (`idSemestre`)
    REFERENCES `Gerenciador`.`Semestre` (`idSemestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Questao_Prova_NivelDeDificuldade1`
    FOREIGN KEY (`idNivelDeDificuldade`)
    REFERENCES `Gerenciador`.`NivelDeDificuldade` (`idNivelDeDificuldade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
